name: webfeed_revised
version: 0.9.0
description: webfeed-revised is a dart package for parsing RSS and Atom feeds. Media, DublinCore, iTunes, Syndication namespaces are also supported.
homepage: https://github.com/Peterkrol12/webfeed-revised
environment:
  sdk: ^3.0.0
dependencies:
  intl: ^0.20.0
  xml: ^6.6.1
dev_dependencies:
  austerity: ^1.2.0
  http: ^1.5.0
  test: ^1.26.3
